# Generated by Django 2.1.7 on 2019-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20190228_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='cartaz',
            field=models.ImageField(upload_to=''),
        ),
    ]
